### PR TITLE
Fix package

### PR DESCRIPTION
**Pull request by luxifer**
- [x] fix typo in package name
- [x] add missing composer description
- [x] move phpunit to require-dev
- [x] apply some phpcs
- [x] remove composer.lock as it should not be committed for library
- [x] fix travis

### CODE REVIEW

**Comment by luxifer** [comment]
The `BlobRestProxy` does not keep the AccountName in the path when using the emulated storage. See:

https://github.com/Azure/azure-storage-php/blob/89e7bcd510c28027c6d8c692c3b90b60d8184531/azure-storage-blob/src/Blob/BlobRestProxy.php#L371-L384

**Comment by luxifer** [comment]
It needs this https://github.com/Azure/azure-storage-php/pull/131 to be merged and released for the tests to pass.

**Comment by luxifer** [comment]
I can confirm that with the fix I made on the storage SDK the tests pass with the emulated storage:

```
$ vendor/bin/phpunit
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.3 with Xdebug 2.6.0
Configuration: /Users/florent/workspace/flysystem-azure-blob-storage/phpunit.xml

.....                                                               5 / 5 (100%)

Time: 950 ms, Memory: 10.00MB

OK (5 tests, 14 assertions)

Generating code coverage report in Clover XML format ... done


Code Coverage Report:
  2018-03-21 09:48:42

 Summary:
  Classes:  0.00% (0/1)
  Methods: 27.27% (6/22)
  Lines:   70.41% (69/98)

\League\Flysystem\AzureBlobStorage::AzureBlobStorageAdapter
  Methods:  27.27% ( 6/22)   Lines:  70.41% ( 69/ 98)
```

**Comment by luxifer** [comment]
Hello there, any news about this package? Everything has been fixed in the dependencies and it works well.

**Comment by frankdejonge** [comment]
Hi @luxifer instead of the docker setup this package is going to be tested against the actual API. The coding style you've applied is not the coding style of this package. There are a few exception like spacer before `!`. I prefer not to have an external .sh file for travis setup because I find it less clear. The thing that indeed needs fixing is the lock exclusion and the require-dev. Could you maybe open a new PR for that instead?

**Comment by luxifer** [comment]
I just see that you addressed the test problem with the 1.1 package for the azure SDK. So I think this PR is not needed anymore. I'm closing it. Have you planned to publish this package on packagist? I'm currently relying on my fork. Regards.

**Pull request closed without merging**
