### PR TITLE
[WIP] v2 adapter 

### PR DESCRIPTION
**Pull request by Brammm**
After seeing the Reddit thread, I decided to try my hand at starting the v2 adaptation. The only thing I'm not sure about is how to handle the visibility thing. 

Still need to change the tests as well.

### CODE REVIEW

**Comment by frankdejonge** [comment]
Hi @Brammm thanks for this! I'm managing the v2 adapter from a mono-repo. Would you want to open up a PR there with this source? This already looks like a very good start, I'll add the visibility abstraction after merging this. This already helps out a lot 👍

**Comment by Brammm** [comment]
@frankdejonge Yeah no problem, but what mono repo are you exactly referring to? Where should I open the PR?

**Comment by frankdejonge** [comment]
@Brammm hey! It's all maintained from https://github.com/thephpleague/flysystem centrally.

**Comment by Brammm** [comment]
Closing in favor of https://github.com/thephpleague/flysystem/pull/1241

**Pull request closed without merging**
