### PR TITLE
Flysystem V2

### LINKED ISSUE #24: V2 support
Hello, any plans for support v2?

### PR DESCRIPTION
**Pull request by Warxcell**
Add support for Flysystem V2.

I didn't tested it, since I don't have Azure Account. 

Fixes #24

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. 

You should make the PR to https://github.com/thephpleague/flysystem instead. You also need to make sure it is working properly.

**Comment by Warxcell** [comment]
> Thank you for this PR.
> 
> You should make the PR to https://github.com/thephpleague/flysystem instead. You also need to make sure it is working properly.

I can move it, but I cannot test it, since I don't have account. Isn't there some account defined in Travis or wherever you run tests, that will test it against real account?

**Comment by Nyholm** [comment]
It is an account on Travis, If you want to write unit tests for everything that would be even better. 

Thank you

**Comment by Warxcell** [comment]
Ok, I will move it to another repo. 
And yes, my changes contains the unit test for adapter.

**Pull request closed without merging**
